# Generated by Django 3.1.3 on 2022-04-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20220405_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('autor', 'question')},
        ),
    ]
